#!/usr/bin/env node
// Reads primitives + semantic tokens and emits:
//   build/web/tokens.css           CSS custom properties, themed via [data-theme=dark].
//   build/web/tailwind.tokens.js   Object consumed by tailwind.config.js.
// Kotlin/Compose output is intentionally not produced here yet — see
// style-dictionary.config.mjs for the placeholder platform.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const srcDir = resolve(pkgRoot, "src");
const webOutDir = resolve(pkgRoot, "build/web");

// Paths whose primitives must never reach the generated outputs. They exist in
// the source file to document the origin of the JSON (they render the device
// frame of the Claude Design mockup), not because the app should style itself
// after them.
const EXCLUDED_PRIMITIVE_PREFIXES = ["radius.device", "shadow.device"];

const isExcluded = (path) => EXCLUDED_PRIMITIVE_PREFIXES.some((p) => path === p || path.startsWith(p + "."));

// Categories inside `_meta` are documentation, not tokens.
const isMeta = (path) => path === "_meta" || path.startsWith("_meta.");

/**
 * Flatten a nested object into `dotted.paths -> leaf` pairs. Skips arrays
 * (typography weights) and the `_meta` documentation block.
 */
function flatten(obj, prefix = "") {
  const out = {};
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (isMeta(path)) continue;
    if (Array.isArray(value)) continue;
    if (value !== null && typeof value === "object") {
      Object.assign(out, flatten(value, path));
    } else {
      out[path] = value;
    }
  }
  return out;
}

/** camelCase -> kebab-case on a single segment. `primaryHover` -> `primary-hover`. */
const kebab = (segment) => segment.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** Path -> CSS custom property name. `color.text.primaryHover` -> `--color-text-primary-hover`. */
const toVar = (path) => "--" + path.split(".").map(kebab).join("-");

/**
 * Serialize a leaf primitive value to CSS text.
 * - Numbers under `spacing.*`, `radius.*` and font `sizes.*` -> pixel string.
 * - Numbers elsewhere (font weights, line heights) -> unitless.
 * - Strings pass through.
 */
function serializePrimitive(path, value) {
  if (typeof value === "number") {
    const usesPx =
      path.startsWith("spacing.") ||
      path.startsWith("radius.") ||
      /\.sizes?\./.test(path) ||
      /\.size$/.test(path);
    return usesPx ? `${value}px` : String(value);
  }
  return String(value);
}

/** Reference from semantic layer -> `var(--...)` pointing at the primitive. */
const primitiveReference = (primitivePath) => `var(${toVar(primitivePath)})`;

function loadJson(file) {
  return JSON.parse(readFileSync(resolve(srcDir, file), "utf8"));
}

// --- primitives ---
const primitives = loadJson("primitives.json");
const flatPrimitives = flatten(primitives);
const usablePrimitives = Object.entries(flatPrimitives).filter(([path]) => !isExcluded(path));

// --- semantic ---
const semantic = loadJson("semantic.json");

/**
 * Walk the semantic tree. Emits two lists of `{ path, light, dark? }` where
 * `light`/`dark` are CSS declarations (e.g. `var(--color-text-light-primary)`).
 */
function collectSemantic(node, prefix = "") {
  const out = [];
  for (const [key, value] of Object.entries(node)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (isMeta(path)) continue;

    if (value && typeof value === "object" && !Array.isArray(value)) {
      const isThemed = "light" in value && "dark" in value;
      if (isThemed) {
        out.push({
          path,
          light: primitiveReference(value.light),
          dark: primitiveReference(value.dark),
        });
      } else {
        out.push(...collectSemantic(value, path));
      }
    } else if (typeof value === "string") {
      out.push({ path, light: primitiveReference(value) });
    } else {
      throw new Error(`Semantic token ${path} must be a string or an object with light/dark.`);
    }
  }
  return out;
}

const semanticTokens = collectSemantic(semantic);

// --- CSS emission ---
const line = (name, value) => `  ${name}: ${value};`;

const primitiveLines = usablePrimitives.map(([path, value]) =>
  line(toVar(path), serializePrimitive(path, value)),
);

const semanticLightLines = semanticTokens.map((t) => line(toVar(t.path), t.light));
const semanticDarkLines = semanticTokens.filter((t) => t.dark).map((t) => line(toVar(t.path), t.dark));

const css = [
  "/* AUTO-GENERATED by packages/design-tokens/scripts/build.mjs — do not edit by hand. */",
  "",
  ":root {",
  "  /* Primitives */",
  ...primitiveLines,
  "",
  "  /* Semantic (light theme) */",
  ...semanticLightLines,
  "}",
  "",
  '[data-theme="dark"] {',
  "  /* Semantic (dark theme overrides) */",
  ...semanticDarkLines,
  "}",
  "",
].join("\n");

// --- Tailwind theme emission ---
// The theme exposes ONLY semantic tokens. Primitives stay hidden so callers
// cannot reach them from utility classes (e.g. no `bg-neutral-300` lands in a
// component by accident).
function nestByPath(entries) {
  const root = {};
  for (const { path, cssVar } of entries) {
    // Tailwind class suffixes read better in kebab-case (`bg-brand-primary-hover`).
    const parts = path.split(".").map(kebab);
    let node = root;
    parts.forEach((part, i) => {
      if (i === parts.length - 1) {
        node[part] = cssVar;
      } else {
        node[part] = node[part] ?? {};
        node = node[part];
      }
    });
  }
  return root;
}

const semanticCssVarEntries = semanticTokens.map((t) => ({
  path: t.path,
  cssVar: `var(${toVar(t.path)})`,
}));

const nested = nestByPath(semanticCssVarEntries);

// Spacing, radius, font sizes and font weights are theme-neutral primitives we
// expose to Tailwind so utilities like `p-lg` / `rounded-md` / `text-base` work.
function collectPrimitiveGroup(prefix, options = {}) {
  const out = {};
  for (const [path, value] of usablePrimitives) {
    if (!path.startsWith(prefix + ".")) continue;
    const suffix = path.slice(prefix.length + 1);
    if (options.filter && !options.filter(suffix, value)) continue;
    const rawKey = options.rename ? options.rename(suffix) : suffix;
    const key = rawKey
      .split("-")
      .map((segment) => kebab(segment))
      .join("-");
    out[key] = options.format ? options.format(value) : value;
  }
  return out;
}

const spacing = collectPrimitiveGroup("spacing", { format: (v) => `${v}px` });
const borderRadius = collectPrimitiveGroup("radius", {
  filter: (suffix) => !suffix.startsWith("device."),
  format: (v) => (v === 9999 ? "9999px" : `${v}px`),
});
const fontSizeBody = collectPrimitiveGroup("typography.body.sizes", { format: (v) => `${v}px` });
const fontSizeDisplay = collectPrimitiveGroup("typography.display.sizes", {
  rename: (suffix) => `display-${suffix}`,
  format: (v) => `${v}px`,
});
const fontSizeMono = collectPrimitiveGroup("typography.mono.sizes", {
  rename: (suffix) => `mono-${suffix}`,
  format: (v) => `${v}px`,
});
const fontSize = { ...fontSizeBody, ...fontSizeDisplay, ...fontSizeMono };

const boxShadow = collectPrimitiveGroup("shadow", { filter: (suffix) => !suffix.startsWith("device.") });

const fontFamily = {
  display: `var(${toVar("font.family.display")})`,
  sans: `var(${toVar("font.family.body")})`,
  mono: `var(${toVar("font.family.mono")})`,
};

const theme = {
  colors: nested.color,
  fontFamily,
  fontSize,
  spacing,
  borderRadius,
  boxShadow,
};

const tailwindOut = [
  "// AUTO-GENERATED by packages/design-tokens/scripts/build.mjs — do not edit by hand.",
  "// Consumed from tailwind.config.js as the source of the theme extension.",
  "",
  `export default ${JSON.stringify(theme, null, 2)};`,
  "",
].join("\n");

// --- write ---
mkdirSync(webOutDir, { recursive: true });
writeFileSync(resolve(webOutDir, "tokens.css"), css);
writeFileSync(resolve(webOutDir, "tailwind.tokens.js"), tailwindOut);

console.log(`Wrote ${primitiveLines.length} primitive vars and ${semanticTokens.length} semantic tokens.`);
console.log(`  ${resolve(webOutDir, "tokens.css")}`);
console.log(`  ${resolve(webOutDir, "tailwind.tokens.js")}`);
